### ISSUE TITLE
Suggestion: Monochrome emojis (Noto emoji?)

### ISSUE THREAD

**Issue by lk251** [syxanash/bluerain#1]
Hi! I love your animation, it's really very cool :) I was wondering if you'd be interested in incorporating Noto Emoji because they're monochrome, I may be outdated and maybe there's a more advanced / modern monochrome emoji font. Not sure if I can help but I'd up for it if you're interested in implementing it! https://fonts.google.com/noto/specimen/Noto+Emoji

My best -lk251

**Comment by syxanash** [comment]
Hi @lk251 this is super cool let me have a look and play with it when I have some time!
In the meantime, thanks for your feedback! <3

**Comment by syxanash** [comment]
I tried using this font but unfortunately some emojis are not directly translated by this font so they would still appear, if you'd like to disable displaying emoji you can press the key <kbd>E</kbd>, while the animation is running. I will try a different approach these days :)

**Comment by lk251** [comment]
thank you! i struggled with this too, it seems like this font doesn't have all the emojis that are currently available in normal fonts. i appreciate your reply and again thanks for a super cool piece of code!!!!
